//{{NO_DEPENDENCIES}}
// Microsoft eMbedded Visual C++ generated include file.
// Used by MultimediaPhone.rc
//
#define IDS_STRING1                     1
#define IDS_STRING2                     2
#define SOUND_DEFAULT_VOLUME            2
#define IDS_STRING3                     3
#define IDS_STRING4                     4
#define IDS_STRING5                     5
#define IDS_STRING6                     6
#define IDS_STRING7                     7
#define IDS_STRING8                     8
#define IDS_STRING9                     9
#define IDS_STRING10                    10
#define IDS_STRING11                    11
#define IDD_MULTIMEDIAPHONE_DIALOG      102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_MAIN                 129
#define IDD_DIALOG_CONTACT              130
#define IDD_DIALOG_SOFTKEY              131
#define IDB_BITMAP_UPARROW              132
#define IDB_BITMAP_DOWNARROW            133
#define IDB_BITMAP_THICK                134
#define IDB_PROGRESS_BAR                135
#define IDB_VOIPINPUTPINYIN             136
#define IDB_VOIPINPUTENG                137
#define IDB_VOIPINPUTENG1               138
#define IDB_VOIPINPUTFUHAO              139
#define IDB_VOIPINPUTH                  140
#define IDD_INPUTDIALOG                 141
#define IDD_DIALOG_INPUT                141
#define IDI_ICON1                       142
#define IDI_ICON2                       143
#define IDD_DIALOG_RECORD               144
#define IDD_DIALOG_CONTACTINFO          144
#define IDD_DIALOG_SOUND                145
#define IDD_DIALOG_SETTING              146
#define IDD_DIALOG_INFORMATION          147
#define IDD_DIALOG_PLAYSOUND            148
#define IDD_DIALOG_SEARCHCINFO          149
#define IDD_DIALOG_SEARCHCONTACTINFO    149
#define IDD_DIALOG_CONTACTINFOSEARCH    149
#define IDD_DIALOG_CONTACTNEW           150
#define IDB_VOIPPYSEARCH                151
#define IDD_DIALOG_CONTACTGROUP         152
#define IDD_DIALOG_MAINMENU             153
#define IDD_DIALOG_CONTACTSEARCH        154
#define IDD_DIALOG_SOUNDSEARCH          155
#define IDD_DIALOG_FASTDIALS            156
#define IDD_DIALOG_FIREWALL             157
#define IDD_DIALOG_TELEPHONE            158
#define IDD_DIALOG_NOTE                 159
#define IDD_DIALOG_PASSWORD             160
#define IDD_DIALOG_DELETETIP            161
#define IDI_ICON_IME                    162
#define IDI_ICON_LINE                   163
#define IDI_ICON_DESK                   164
#define IDI_ICON_CONTACT                165
#define IDI_ICON_CONTACTINFO            166
#define IDI_ICON_SOUND                  167
#define IDI_ICON_INFO                   168
#define IDI_ICON_SETTING                169
#define WM_DEVICECHANGE                 537
#define IDC_BUTTONTIME                  1000
#define IDC_BUTTON_TIME                 1000
#define IDC_BUTTONIME                   1001
#define IDC_BUTTON_IME                  1001
#define IDC_BUTTONLINE                  1002
#define IDC_BUTTON_LINE                 1002
#define IDC_BUTTONMAIN                  1003
#define IDC_BUTTON_MAIN                 1003
#define IDC_BUTTONCONTACT               1004
#define IDC_BUTTON_CONTACT              1004
#define IDC_BUTTONHISTORY               1005
#define IDC_BUTTON_CONTACTINFO          1005
#define IDC_BUTTONRECORD                1006
#define IDC_BUTTON_SOUND                1006
#define IDC_BUTTONINFO                  1007
#define IDC_BUTTON_INFORMATION          1007
#define IDC_BUTTONSETTING               1008
#define IDC_BUTTON_SETTING              1008
#define IDC_BUTTON_CONTACTNEW           1009
#define IDC_BUTTON_CONTACTGROUP         1010
#define IDC_SLIDER1                     1011
#define IDC_PROGRESS1                   1012
#define IDC_LIST_TYPE                   1015
#define IDC_LIST_LIST                   1016
#define IDC_STATIC_TIME                 1017
#define IDC_STATIC_TODAY                1021
#define IDC_STATIC_TELSTATUS            1022
#define IDC_STATIC_CALLWALL             1023
#define IDC_STATIC_LINE                 1024
#define IDC_BUTTON_SOUNDDLG_CLOSE       1031
#define IDC_BUTTON_SOUNDDLG_PREV        1032
#define IDC_BUTTON_SOUNDDLG_NEXT        1033
#define IDC_BUTTON_SOUNDDLG_PLAY        1034
#define IDC_CHECK_SOUNDDLG_PLAYCONTINUE 1035
#define IDC_LIST_CONTACTINFO_TYPE       1041
#define IDC_LIST_CONTACTINFO_LIST       1042
#define IDC_BUTTON_CONTACTINFO_DIAL     1043
#define IDC_BUTTON_CONTACTINFO_NOTE     1044
#define IDC_BUTTON_CONTACTINFO_NEW      1045
#define IDC_BUTTON_CONTACTINFO_SEARCH   1046
#define IDC_BUTTON_CONTACTINFO_DELETE   1047
#define IDC_BUTTON_CONTACTINFO_SOUND    1048
#define IDC_STATIC_CONTACTINFOSEARCH_TITLE 1053
#define IDC_DATETIME_CONTACTINFOSEARCH_FROM 1054
#define IDC_DATETIME_CONTACTINFOSEARCH_TO 1055
#define IDC_EDIT_CONTACTINFOSEARCH_NAME 1056
#define IDC_EDIT_CONTACTINFOSEARCH_NUMBER 1057
#define IDC_BUTTON_CONTACTINFOSEARCH_CANCEL 1058
#define IDC_BUTTON_CONTACTINFOSEARCH_SEARCH 1059
#define IDC_STATIC_CONTACT_PINYIN       1063
#define IDC_SOFTKEY_CONTACT_PYSEARCH    1064
#define IDC_LIST_CONTACT_TYPE           1065
#define IDC_LIST_CONTACT_LIST           1066
#define IDC_BUTTON_CONTACT_NEW          1067
#define IDC_BUTTON_CONTACT_NEWTYPE      1068
#define IDC_BUTTON_CONTACT_EDITTYPE     1069
#define IDC_BUTTON_CONTACT_SEARCH       1070
#define IDC_EDIT_CONTACTNEW_TELEPHONE1  1071
#define IDC_EDIT_CONTACTNEW_TELEPHONE2  1072
#define IDC_EDIT_CONTACTNEW_EMAIL       1073
#define IDC_EDIT_CONTACTNEW_SITE        1074
#define IDC_EDIT_CONTACTNEW_COMPANY     1075
#define IDC_EDIT_CONTACTNEW_ADDRESS     1076
#define IDC_EDIT_CONTACTNEW_POSTCODE    1077
#define IDC_EDIT_CONTACTNEW_DEPARTMENT  1078
#define IDC_EDIT_CONTACTNEW_DUTY        1079
#define IDC_EDIT_CONTACTNEW_MEMO        1080
#define IDC_BUTTON_CONTACTNEW_OK        1081
#define IDC_BUTTON_CONTACTNEW_CANCEL    1082
#define IDC_BUTTON_CONTACTNEW_DELETE    1083
#define IDC_EDIT_CONTACTNEW_NAME        1084
#define IDC_EDIT_CONTACTNEW_MOBILE1     1085
#define IDC_EDIT_CONTACTNEW_MOBILE2     1086
#define IDC_COMBOBOX_CONTACTNEW_TYPE    1087
#define IDC_COMBOBOX_CONTACTNEW_GROUP   1088
#define IDC_BUTTON_CONTACTNEW_DIALMOBILE1 1089
#define IDC_BUTTON_CONTACTNEW_DIALMOBILE2 1090
#define IDC_BUTTON_CONTACTNEW_DIALTEL1  1091
#define IDC_BUTTON_CONTACTNEW_DIALTEL2  1092
#define IDC_LIST_SOUND_TYPE             1094
#define IDC_LIST_SOUND_LIST             1095
#define IDC_BUTTON_SOUND_SOUND          1096
#define IDC_BUTTON_SOUND_SEARCH         1097
#define IDC_BUTTON_SOUND_PROTECT        1098
#define IDC_BUTTON_SOUND_DELETE         1099
#define IDC_LIST_SETTING_TYPE           1100
#define IDC_BUTTON_SETTING_OK           1101
#define IDC_BUTTON_SETTING_CANCEL       1102
#define IDC_BUTTON_SETTING_DEFAULT      1103
#define IDC_BUTTON_SETTING_CLEARCONTACT 1104
#define IDC_BUTTON_SETTING_CLEARCONTACTINFO 1105
#define IDC_BUTTON_SETTING_CLEARSOUND   1106
#define IDC_BUTTON_SETTING_CLEARINFO    1107
#define IDC_COMBOBOX_SETTING_SOUNDSAVEPATH 1108
#define IDC_BUTTON_CONTACTGROUP_OK      1200
#define IDC_BUTTON_CONTACTGROUP_CANCEL  1201
#define IDC_BUTTON_CONTACTGROUP_DELETE  1202
#define IDC_COMBOBOX_CONTACTGROUP_RING  1203
#define IDC_COMBOBOX_CONTACTGROUP_SOUNDTIP 1204
#define IDC_EDIT_CONTACTGROUP_NAME      1205
#define IDC_BUTTON_CONTACTSEARCH_SEARCH 1300
#define IDC_BUTTON_CONTACTSEARCH_CANCEL 1301
#define IDC_EDIT_CONTACTSEARCH_NAME     1302
#define IDC_EDIT_CONTACTSEARCH_NUMBER   1303
#define IDC_EDIT_CONTACTSEARCH_COMPANY  1304
#define IDC_EDIT_CONTACTSEARCH_DUTY     1305
#define IDC_BUTTON_SOUNDSEARCH_CANCEL   1400
#define IDC_BUTTON_SOUNDSEARCH_SEARCH   1401
#define IDC_DATETIME_SOUNDSEARCH_FROM   1402
#define IDC_DATETIME_SOUNDSEARCH_TO     1403
#define IDC_EDIT_SOUNDSEARCH_NAME       1404
#define IDC_EDIT_SOUNDSEARCH_NUMBER     1405
#define IDC_EDIT_FASTDIALS_NUMBER01     1501
#define IDC_EDIT_FASTDIALS_NUMBER02     1502
#define IDC_EDIT_FASTDIALS_NUMBER03     1503
#define IDC_EDIT_FASTDIALS_NUMBER04     1504
#define IDC_EDIT_FASTDIALS_NUMBER05     1505
#define IDC_EDIT_FASTDIALS_NUMBER06     1506
#define IDC_EDIT_FASTDIALS_NUMBER07     1507
#define IDC_EDIT_FASTDIALS_NUMBER08     1508
#define IDC_EDIT_FASTDIALS_NUMBER09     1509
#define IDC_EDIT_FASTDIALS_NUMBER10     1510
#define IDC_EDIT_FASTDIALS_NUMBER11     1511
#define IDC_EDIT_FASTDIALS_NUMBER12     1512
#define IDC_BUTTON_FASTDIALS_OK         1600
#define IDC_BUTTON_FASTDIALS_CANCEL     1601
#define IDC_BUTTON_FIREWALL_OK          1700
#define IDC_BUTTON_FIREWALL_CANCEL      1701
#define IDC_CHECKBOX_FIREWALL_ENABLE    1702
#define IDC_CHECKBOX_FIREWALL_BLACKLIST 1703
#define IDC_CHECKBOX_FIREWALL_CONTACT   1704
#define IDC_CHECKBOX_FIREWALL_VIP       1705
#define IDC_CHECKBOX_FIREWALL_ALL       1706
#define IDC_COMBO_FIREWALL_TIME         1707
#define IDC_BUTTON_TELEPHONE_HIDE       1800
#define IDC_BUTTON_TELEPHONE_NOTE       1801
#define IDC_BUTTON_TELEPHONE_RECORD     1802
#define IDC_BUTTON_TELEPHONE_HANDLE     1803
#define IDC_BUTTON_TELEPHONE_RECORDTIP  1804
#define IDC_STATIC_TELEPHONE_TITLE      1806
#define IDC_STATIC_TELEPHONE_NAMENO     1807
#define IDC_STATIC_TELEPHONE_COMPANY    1808
#define IDC_STATIC_TELEPHONE_DEPARTMENT 1809
#define IDC_STATIC_TELEPHONE_DUTY       1810
#define IDC_BUTTON_NOTE_OK              1900
#define IDC_BUTTON_NOTE_PREV            1901
#define IDC_BUTTON_NOTE_NEXT            1902
#define IDC_BUTTON_NOTE_CLEAR           1903
#define IDC_STATIC_NOTE_PAGENUMBER      1904
#define IDC_BUTTON_PASSWORD_OK          2000
#define IDC_BUTTON_PASSWORD_CANCEL      2001
#define IDC_BUTTON_DELETETIP_OK         2005
#define IDC_BUTTON_DELETETIP_CANCEL     2006
#define IDC_EDIT_DELETETIP_PASSWORD     2007
#define IDC_BUTTON1                     3033
#define IDC_BUTTON2                     3034
#define IDC_BUTTON3                     3035
#define IDC_BUTTON4                     3036
#define IDC_BUTTON5                     3037
#define IDC_BUTTON6                     3038
#define IDC_STATIC_CUSTOMER             3040
#define IDC_EDIT_SETTING_AREANO         3104
#define IDC_CHECK_SETTING_OUTLINE       3105
#define IDC_EDIT_SETTING_OUTLINE        3106
#define IDC_CHECK_SETTING_IPDIAL        3107
#define IDC_EDIT_SETTING_IPDIAL         3108
#define IDC_CHECK_SETTING_RING          3109
#define IDC_COMBOBOX_SETTING_RING       3110
#define IDC_CHECK_SETTING_AUTOLEAVEWORD 3111
#define IDC_COMBOBOX_SETTING_RINGTIMES  3112
#define IDC_COMBOBOX_SETTING_AUTOLEAVEWORD 3113
#define IDC_BUTTON_SETTING_RECORD       3114
#define IDC_BUTTON_SETTING_DEFINEFASTDAIL 3115
#define IDC_RADIO_SETTING_CONNECTAUTO   3116
#define IDC_RADIO_SETTINT_CONNECTADSL   3117
#define IDC_EDIT_SETTING_ADSLNAME       3118
#define IDC_EDIT_SETTING_ADSLPASSWORD   3119
#define IDC_RADIO_SETTING_DHCP          3200
#define IDC_RADIO_SETTING_STATIC        3201
#define IDC_EDIT_SETTING_IP             3202
#define IDC_EDIT_SETTING_MASK           3203
#define IDC_EDIT_SETTING_GATEWAY        3204
#define IDC_EDIT_SETTING_DNS            3205
#define IDC_CHECK_SETTING_SCREENPROTECT 3206
#define IDC_RADIO_SETTING_TIMESCREEN    3207
#define IDC_RADIO_SETTING_IMAGESCREEN   3208
#define IDC_COMBOBOX_SETTING_WAITTIME   3209
#define IDC_CHECK_SETTING_SPPASSWORD    3210
#define IDC_BUTTON_SETTING_SETPASSWORD  3219
#define IDC_BUTTON_SETTING_ADJUSTTOUCH  3220
#define IDC_BUTTON_SETTING_PLAY         3221
#define IDC_BUTTON_CONTACT_CLOSE        3222
#define IDC_BUTTON_CONTACTINFO_CLOSE    3223
#define IDC_BUTTON_SOUND_CLOSE          3224
#define IDC_BUTTON_NOTE_CLOSE           3225
#define IDT_GETINFO_TIIMER              8000
#define IDT_PAUSE_PLAYER                8001
#define WM_CHANGEWINDOW                 8001
#define IDT_CLICKLIST_TIMER             8002
#define WM_PLAYVIDEO                    8002
#define IDT_SCREENSAVE_TIME             8003
#define WM_PLAYPHOTO                    8003
#define IDT_SCREENSAVE_INPUTTIME        8004
#define WM_TEL_RING                     8020
#define WM_TEL_HUNGON                   8021
#define WM_TEL_HUNGOFF                  8022
#define WM_TEL_CALLIDEND                8023
#define WM_TEL_TELCODE                  8024
#define WM_TEL_KEYCODE                  8025
#define WM_LUNAR_CLICKED                8026
#define WM_COMMBOX_CLICKED              8027
#define WM_SETTINGPASSWORD              8028
#define WM_CHECKPASSWORD                8029
#define WM_OUTEVENT                     8030
#define WM_STATIC_CLICK                 8031
#define WM_GEN_EVENT                    8032
#define WM_TOUCH_CLICK                  8033
#define IDD_DIALOG_CEDLG                8053
#define IDB_BITMAP_MASK                 8054
#define IDD_DIALOG_PLAYER               8056
#define IDD_DIALOG_TESTCEDLG            8057
#define IDI_ICON_VIDEO                  8058
#define IDI_ICON_SAVESCREEN             8059
#define IDI_ICON_PHOTO                  8060
#define IDC_TEST_LISTBOX                8060
#define IDI_ICON_MP3                    8061
#define IDC_LIST_MEMORY                 8061
#define IDI_ICON_CANL                   8062
#define ID_BTN_TEST_CALL                8062
#define IDI_ICON_CALU                   8063
#define ID_BTN_TEST_DB                  8063
#define ID_BTN_TEST_EXIT                8064
#define IDB_BITMAP_DOWNARROW1           8900
#define IDD_DIALOG_VIDEO                8900
#define IDB_BITMAP_THICK1               8901
#define IDD_DIALOG_PHOTO                8901
#define IDD_DIALOG_MP3                  8902
#define IDB_BITMAP_UPARROW1             8903
#define IDI_ICON_EXIT                   8903
#define IDC_BUTTON_VIDEOEXIT            8904
#define IDI_ICON_CHECK1                 8904
#define IDC_BUTTON_VIDEOALL             8905
#define IDI_ICON_PRE                    8905
#define IDC_BUTTON_VIDEOCLEAR           8906
#define IDI_ICON_CHECK0                 8906
#define IDC_BUTTON_VIDEOPRE             8907
#define IDI_ICON_SOUNDOK                8907
#define IDC_BUTTON_VIDEOPLAY            8908
#define IDI_ICON_NEXT                   8908
#define IDC_BUTTON_VIDEOBACK            8909
#define IDI_ICON_PLAY                   8909
#define IDC_BUTTON_VIDEOMUTE            8910
#define IDC_BUTTON_MP3MUTE              8910
#define IDI_ICON_STOPPLAY               8910
#define IDC_PROGRESS_VIDEOTIME          8911
#define IDC_PROGRESS_MP3TIME            8911
#define IDC_PROGRESS_VIDEOSOUND         8912
#define IDC_PROGRESS_MP3SOUND           8912
#define IDI_ICON_SOUNDCACEL             8912
#define IDC_LIST_PLAYLIST               8913
#define IDB_BITMAP_RADIO2               8913
#define IDC_BUTTON_VIDEOOPEN            8914
#define IDB_BITMAP_COMBOBOX             8914
#define IDC_BUTTON_VIDEOPLAYALL         8915
#define IDB_BITMAP_RADIO1               8915
#define IDC_BUTTON_PHOTOEXIT            8916
#define IDI_ICON_COMBOBOX               8916
#define IDC_BUTTON_PHOTOALL             8917
#define IDD_DIALOG_LUNARDER             8917
#define IDC_BUTTON_PHOTOCLEAR           8918
#define IDD_DIALOG_SCREENSAVE           8918
#define IDC_BUTTON_PHOTOPRE             8919
#define IDD_DIALOG_CACULATER            8919
#define IDC_BUTTON_PHOTOPLAY            8920
#define IDB_BITMAP_CALCULATOR           8920
#define IDC_BUTTON_PHOTOBACK            8921
#define IDC_LIST_PLAYPHOTOLIST          8922
#define IDC_BUTTON_PHOTOOPEN            8923
#define IDC_BUTTON_PHOTOPLAYALL         8924
#define IDB_BITMAP_MAINTOGGLE           8924
#define IDC_BUTTON_MP3EXIT              8925
#define IDB_BITMAP_MAINRECORD           8925
#define IDC_BUTTON_MP3ALL               8926
#define IDB_BITMAP_MAINSETTING          8926
#define IDC_BUTTON_MP3CLEAR             8927
#define IDB_BITMAP_MAINTEL              8927
#define IDC_BUTTON_MP3PRE               8928
#define IDB_BITMAP_MAINCALLLIST         8928
#define IDC_BUTTON_MP3PLAY              8929
#define IDB_BITMAP_MAINCARD             8929
#define IDC_BUTTON_MP3BACK              8930
#define IDB_BITMAP_MAINDESKTOP          8930
#define IDC_LIST_MP3LIST                8931
#define IDB_BITMAP_MAININFO             8931
#define IDC_BUTTON_MP3OPEN              8932
#define IDB_BITMAP_MAININPUT            8932
#define IDC_BUTTON_LUNARDEREXIT         8933
#define IDB_BITMAP_MAIN                 8933
#define IDC_LUNARDER_LUNARDER           8934
#define IDB_BITMAP_MP3PROGRESS_TOP1     8934
#define IDC_BUTTON_PHOTOSCREENSAVE      8935
#define IDB_BITMAP_MP3SOUND_BOTTOM1     8935
#define IDC_EDIT_SCREENSAVE             8936
#define IDB_BITMAP_MP3SOUND_TOP1        8936
#define IDC_CALCULATOR_SOFTKEY          8937
#define IDB_BITMAP_MP3VPROGRESS_BOTTOM1 8937
#define IDC_BUTTON_CALUEXIT             8938
#define IDB_BITMAP_MP3VPROGRESS_TOP1    8938
#define IDB_BITMAP_ARC_BOTTOM1          8939
#define IDB_BITMAP_ARC_TOP1             8940
#define IDB_BITMAP_PLAY_BOTTOM1         8941
#define IDB_BITMAP_PLAY_TOP1            8942
#define IDB_BITMAP_MP3PROGRESS_BOTTOM1  8943
#define IDB_BITMAP_MAINTIME             8945
#define IDB_BITMAP_MAIN_TXTBAR1         8946
#define IDB_BITMAP_MAINVIDEO            8947
#define IDB_BITMAP_MAINMP3              8948
#define IDB_BITMAP_MAINPHOTO            8949
#define IDB_BITMAP_MAINCALU             8950
#define IDB_BITMAP_MAINSAVE             8951
#define IDB_BITMAP_MAINCAND             8952
#define IDB_BITMAP_COMBOX_UP1           8953
#define IDB_BITMAP_COMBOX_DOWN1         8954
#define IDB_BITMAP_MP3_SELECT_UP1       8955
#define IDB_BITMAP_MP3_SELECT_DOWN1     8956
#define IDB_BITMAP_SELECT1              8957
#define IDB_BITMAP_RECT_UP1             8958
#define IDB_BITMAP_RECT_DOWN1           8959
#define IDB_BITMAP_DIAL_UP1             8960
#define IDB_BITMAP_DIAL_DOWN1           8961
#define IDB_BITMAP_UNSELECT1            8962
#define IDB_BITMAP_EXIT_DOWN1           8963
#define IDB_BITMAP_EXIT_UP1             8964
#define IDB_BITMAP_EXIT1_UP1            8965
#define IDB_BITMAP_EXIT1_DOWN1          8966
#define IDB_BITMAP_RIGHT_DOWN1          8967
#define IDB_BITMAP_LEFT_UP1             8968
#define IDB_BITMAP_LEFT_DOWN1           8969
#define IDB_BITMAP_RIGHT_UP1            8970
#define IDB_BITMAP_UP_DOWN1             8971
#define IDB_BITMAP_DOWN_UP1             8972
#define IDB_BITMAP_DOWN_DOWN1           8973
#define IDB_BITMAP_UP_UP1               8974
#define IDC_LUNARDER_OK                 8975
#define IDB_BITMAP27                    8975
#define IDC_LUNARDER_CANCEL             8976
#define IDB_BITMAP28                    8976
#define IDC_LUNARDER_DELETE             8977
#define IDB_BITMAP29                    8977
#define IDB_BITMAP30                    8978
#define IDB_BITMAP_LISTDIR              8979
#define IDB_BITMAP_LISTTOBOTTOM         8980
#define IDB_BITMAP_LISTCIPAN            8981
#define IDB_BITMAP1                     8982
#define IDB_BITMAP2                     8983
#define IDB_BITMAP3                     8984
#define IDB_BITMAP4                     8985
#define IDB_BITMAP6                     8986
#define IDB_BITMAP5                     8987
#define IDB_BITMAP7                     8988
#define IDB_BITMAP8                     8989
#define IDB_BITMAP9                     8990
#define IDB_BITMAP10                    8991
#define IDB_BITMAP11                    8992
#define IDB_BITMAP12                    8993
#define IDB_BITMAP13                    8994
#define IDB_BITMAP14                    8995
#define IDB_BITMAP15                    8996
#define IDB_BITMAP16                    8997
#define IDB_BITMAP17                    8998
#define IDB_BITMAP18                    8999
#define IDB_BITMAP19                    9000
#define IDB_BITMAP20                    9001
#define IDB_BITMAP21                    9002
#define IDB_BITMAP22                    9003
#define IDB_BITMAP23                    9004
#define IDB_BITMAP24                    9005
#define IDB_BITMAP25                    9006
#define IDB_BITMAP26                    9007
#define IDC_SETTING_DATE                9008
#define IDC_SETTING_TIME                9009
#define IDB_BITMAP3_MUSIC               9009
#define IDC_SETTING_BACKUP              9010
#define IDB_BITMAP31                    9010
#define IDC_SETTING_RESTORE             9011
#define IDB_BITMAP32                    9011
#define IDD_DIALOG_COPYFILE             9011
#define IDC_SETTING_CMBSELECT           9012
#define IDB_BITMAP_ARC_BOTTOM3          9012
#define IDC_SETTING_DELETE              9013
#define IDB_BITMAP_ARC_BOTTOM2          9013
#define IDC_SETTING_ALLSELECT           9014
#define IDB_BITMAP_ARC_TOP3             9014
#define IDC_SETTING_CLEARSELECT         9015
#define IDB_BITMAP_ARC_TOP2             9015
#define IDC_SETTING_IN                  9016
#define IDB_BITMAP_ARC_TOP4             9016
#define IDC_SETTING_OUT                 9017
#define IDB_BITMAP_ARC_BOTTOM4          9017
#define IDC_SETTING_LSTLOCAL            9018
#define IDC_SETTING_LSTUSB              9019
#define IDC_SETTING_LSTRING             9020
#define IDC_SETTING_RINGSELECT          9021
#define IDC_SETTING_PASSWORD1           9022
#define IDC_SETTING_PASSWORD2           9023
#define IDC_SETTING_PASSWORD3           9024
#define IDC_STATIC_NOTETATUS            9025
#define IDB_BITMAP_SETTINGINOUT         9026
#define IDT_MAIN_SAVESCREEN_TIME        9027
#define IDC_BUTTON_MAINNOTE             9028
#define IDC_SHOWPLYERDLG_TIMER          9029
#define IDC_SETTING_VERSION             9030
#define IDC_SETTING_EDITVERSION         9031
#define IDT_DETECTUSB                   9032
#define WM_USB_MSG                      9034
#define WM_DELETESELITEM                9040
#define WM_TELNOTIFY                    9041
#define WM_FIRENOTIFY                   9042
#define WM_SPEEDDIAL                    9043
#define WM_REDIAL                       9044
#define WM_MUTE                         9045
#define WM_RKEY                         9046
#define WM_HUNGONINRECORD               9047
#define IDT_SHOWSTOCKS_TIMER            9048
#define IDT_COPYFILE_TIMER              9049
#define WM_HUNGONTORECORD               9050
#define IDD_DIALOG_NOTEBOOK             9051
#define IDD_DIALOG_WEB                  9052
#define WM_CLICKMJPG_TOAPP              9053
#define IDB_BITMAP_WHSTATIC             9053
#define WM_MJPGSHOWHALF                 9054
#define IDD_DIALOG_RECORDSOUND          9054
#define WM_TEL_INUSE                    9055
#define IDB_BITMAP_PROGRESS_BAR1        9055
#define WM_TEL_NOUSE                    9056
#define IDB_BITMAP_PROGRESS_BAR2        9056
#define WM_LOCALRECORD                  9057
#define IDD_DIALOG_SIMIMPORT            9057
#define WM_PLAYLEAVEWORD                9058
#define IDD_DIALOG_ALARM                9058
#define IDC_BUTTON_SOUND_RECORD         9059
#define IDD_DIALOG_HUANGLI              9059
#define IDC_BUTTON_SOUND_SETTIP         9060
#define IDC_BUTTON_RECORDDLG_CLOSE      9061
#define IDB_PROGRESS_VOLUME1            9061
#define IDC_BUTTON_RECORDDLG_CLEAR      9062
#define IDB_PROGRESS_TIME1              9062
#define IDC_BUTTON_RECORDDLG_PLAY       9063
#define IDB_PROGRESS_TIME2              9063
#define IDC_BUTTON_RECORDDLG_RECORD     9064
#define IDB_PROGRESS_TIME_THINCK        9064
#define IDC_PBAR_RECORDDLG_PROCESS      9065
#define IDB_PROGRESS_VOLUMETHINCK       9065
#define IDC_PBAR_SOUNDDLG_PROCESS       9066
#define IDD_DIALOG_RENAME               9066
#define WM_SIMDATA_OK                   9067
#define IDB_BITMAP_LEFTARROW            9067
#define WM_SIMDATA_ERROR                9068
#define IDB_BITMAP_RIGHTARROW           9068
#define WM_LISTCTRL_CLICK               9069
#define IDB_BITMAP_RIGHTARROWD          9069
#define IDT_ALARMTIME                   9070
#define IDB_BITMAP_LEFTARROWD           9070
#define WM_SENDSIMCMD                   9071
#define IDD_DIALOG_NETSTATUS            9071
#define WM_EDITENTER                    9072
#define IDD_DIALOG_NOFLASH              9072
#define WM_KILLWEBSHOW                  9073
#define IDD_DIALOG_TEST                 9073
#define WM_RENAME                       9074
#define IDT_CONTROLBACKLIGHT_TIME       9075
#define WM_STOPTRYRING                  9076
#define WM_BTNST_CLICK                  9077
#define IDC_SETTING_BLACKSCREEN1        9078
#define WM_SCROLL_EDO                   9078
#define IDC_SETTING_BLACKSCREEN2        9079
#define WM_BINGJIZHAIJI                 9079
#define WM_MJPGMOVE						9080
#define IDC_EDIT_SETTINGPLAYPASSWORD	9081
#define IDC_EDIT_SETTINGSUPPERPASSWORD  9082
#define IDC_CHECK_SETTING_PLAYPROTECT	9083
#define IDC_CHECK_SETTING_ADNINPROTECT	9084
#define IDC_RADIO_SETTING_RECORDAUTO	9085
#define IDC_RADIO_SETTING_RECORDMANUL   9086
#define IDC_RADIO_SETTING_RECORDHIGHT	9087
#define IDC_RADIO_SETTING_RECORDMIDDLE  9088
#define WM_CLEARPWD						9081
#define WM_FORMATDATA					9082
#define WM_NOPENUP						9083

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        9075
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         8065
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
