// Machine generated IDispatch wrapper class(es) created by Microsoft Visual C++

// NOTE: Do not modify the contents of this file.  If this class is regenerated by
//  Microsoft Visual C++, your modifications will be overwritten.


#include "stdafx.h"
#include "explorer_browser.h"

namespace Logical {
    /////////////////////////////////////////////////////////////////////////////
    // CExplorer_browser

    IMPLEMENT_DYNCREATE(CExplorer_browser, CWnd)

        /////////////////////////////////////////////////////////////////////////////
        // CExplorer_browser properties

        /////////////////////////////////////////////////////////////////////////////
        // CExplorer_browser operations
}
