#ifndef __DOC_HEADER_FILE_
#define __DOC_HEADER_FILE_
#define     HELP_MAIN      257   
#define     HELP_CARDCASE_MAIN      258   
#define     HELP_CARDCASE_SETUP      259   
#define     HELP_CARDCASE_SETUP_DETAIL      260   
#define     HELP_CARDCASE_SORT      261   
#define     HELP_CARDCASE_DEL      262   
#define     HELP_SEARCH_CARD      263   
#define     HELP_SEARCH_RESULT      264   
#define     HELP_CARDCASE_CARD_LIST      265   
#define     HELP_CARD_COPYTO      266   
#define     HELP_CARD_MOVETO      267   
#define     HELP_CARD_CHOICE_DESTINATION      268   
#define     HELP_CARD_DEL      269   
#define     HELP_CARD_NEW      270   
#define     HELP_CARD_BROWSER      271   
#define     HELP_CARD_EDIT      272   
#define     HELP_SMS_MAIN      273   
#define     HELP_SMS_BOX      274   
#define     HELP_SMS_BOX_SETUP      275   
#define     HELP_SMS_BOX_SETUP_DETAIL      276   
#define     HELP_SMS_BOX_DETAIL      277   
#define     HELP_SMS_WRITE      278   
#define     HELP_SMS_COLLECTION      279   
#define     HELP_SMS_COLLECTION_RENAME      280   
#define     HELP_SMS_COLLECTION_DEL      281   
#define     HELP_SMS_COLLECTION_SORT      282   
#define     HELP_SMS_COLLECTION_PHRASE      283   
#define     HELP_SMS_SEND_GROUP      284   
#define     HELP_SMS_SEND_GROUP_RENAME      285   
#define     HELP_SMS_SEND_GROUP_DEL      286   
#define     HELP_SMS_SEND_GROUP_SORT      287   
#define     HELP_SMS_SEND_GROUP_EDIT      288   
#define     HELP_SMS_JIAJIAE      289   
#define     HELP_SMS_ESMS      290   
#define     HELP_SMS_SETUP      291   
#define     HELP_HISTORY_MAIN      292   
#define     HELP_HISTORY_DETAIL      293   
#define     HELP_ALARM_MAIN      294   
#define     HELP_ALARM_ONCE      295   
#define     HELP_ALARM_NEWOREDIT      296   
#define     HELP_ALARM_EVERYDAY      297   
#define     HELP_ALARM_EVERYWEEK      298   
#define     HELP_ALARM_EVERYMONTH      299   
#define     HELP_ALARM_EVERYYEAR      300   
#define     HELP_ALARM_BROWSER      301   
#define     HELP_ALARM_TODAY      302   
#define     HELP_ALARM_MONTH      303   
#define     HELP_ALARM_OK      304   
#define     HELP_MEMO_MAIN      305   
#define     HELP_MEMO_NEW      306   
#define     HELP_MEMO_BROWSER      307   
#define     HELP_PICTURE_MAIN      308   
#define     HELP_PICTURE_BROWSER      309   
#define     HELP_CLOCK      310   
#define     HELP_CALENDAR      311   
#define     HELP_RECBROWSE      312   
#define     HELP_RECORD_DETAIL      313   
#define     HELP_RECORD_DETAIL_PLAY      314   
#define     HELP_CALCULATOR      315   
#define     HELP_UNIT      316   
#define     HELP_SETUP      317   
#define     HELP_SETUP_TIME      318   
#define     HELP_SETUP_DATE      319   
#define     HELP_SETUP_RECORD      320   
#define     HELP_SETUP_RECORD_WELCOME      321   
#define     HELP_SETUP_RING      322   
#define     HELP_SETUP_DIALSTOP      323   
#define     HELP_SETUP_EXTERIOR_LINE      324   
#define     HELP_SETUP_ONLY_RING      325   
#define     HELP_SETUP_IP      326   
#define     HELP_SETUP_LOCK      327   
#define     HELP_SETUP_MEM      328   
#define     HELP_DOCUMENT      329   
#define     ID_DOC_YOUBIAN      330   
#define     ID_DOC_QUHAO      331   
#define     ID_DOC_PHONE      332   
#define     ID_DOC_XINGZUO      333   
#define     ID_DOC_SHUXIANG      334   
#define     ID_DOC_XUEXING      335   
#define     ID_DOC_HISTORY      336   
#define     ID_DOC_HOLIDAY      337   
#define     ID_DOC_WORLDAREA      338   
#define DOC_ID_START         257
#define DOC_ID_END       338
#endif
